apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: chaos-app-pod-failure
  namespace: chaos-lab
spec:
  action: pod-failure
  mode: one
  duration: 30s
  selector:
    namespaces:
      - chaos-lab
    labelSelectors:
      app: chaos-app
