apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: mariadb-pod-kill-one
  namespace: chaos-lab
  labels:
    chaos_name: mariadb-pod-kill-one
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - chaos-lab
    labelSelectors:
      app: mariadb
  duration: "60s"
