apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: chaos-app-cpu-stress-one-high
  namespace: chaos-lab
  labels:
    chaos_name: chaos-app-cpu-stress-one-high
spec:
  mode: one
  selector:
    namespaces:
      - chaos-lab
    labelSelectors:
      app: chaos-app
  duration: "60s"
  stressors:
    cpu:
      workers: 2
      load: 100

