apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: chaos-app-network-corrupt-all
  namespace: chaos-lab
  labels:
    chaos_name: chaos-app-network-corrupt-all
spec:
  action: corrupt
  mode: all
  selector:
    namespaces:
      - chaos-lab
    labelSelectors:
      app: chaos-app
  corrupt:
    corrupt: "25"
  duration: "60s"
