apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: memory-high-one-new
  namespace: chaos-lab
spec:
  mode: one
  duration: "60s"
  selector:
    namespaces:
      - chaos-lab
    labelSelectors:
      app: chaos-app
  stressors:
    memory:
      workers: 1
      size: "256MB"
