apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: memory-chaos-test
  namespace: chaos-lab
spec:
  mode: one
  selector:
    namespaces:
      - chaos-lab
    labelSelectors:
      app: chaos-app
  stressors:
    memory:
      workers: 1
      size: 128MB
  duration: "60s"
