apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mariadb-exporter
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - chaos-lab
  selector:
    matchLabels:
      app: mariadb-exporter
  endpoints:
    - port: metrics
      interval: 30s
