apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: chaos-app-io-latency-one
  namespace: chaos-lab
  labels:
    chaos_name: chaos-app-io-latency-one
spec:
  action: latency
  mode: one
  selector:
    namespaces:
      - chaos-lab
    labelSelectors:
      app: chaos-app
  volumePath: /data
  path: /data/**
  delay: "100ms"
  percent: 100
  duration: "60s"
