apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: chaos-app-memory-high-one
  namespace: chaos-lab
spec:
  mode: one
  selector:
    namespaces:
      - chaos-lab
    labelSelectors:
      app: chaos-app
  stressors:
    memory:
      workers: 2
      size: "512MB"
  duration: "60s"
